[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Bohui Moon <bohuimoon@gmail.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
regex = "1.0.0"
rust-crypto = "0.2.36"
